name: densitymatch
channels:
  - pytorch
  - conda-forge
  - open3d-admin
  - nvidia
dependencies:
  - python=3.9
  - ipython
  - pip

  - numpy
  - scipy
  - pandas

  - matplotlib
  - seaborn

  - rdkit
  - openbabel
  - spyrmsd

  - cudatoolkit=11.3
  - pytorch

  - py3Dmol

  - jupyter

  - pip:
    - open3d
    - molgrid
