name: densitymatch
channels:
  - conda-forge
  - pytorch
  - open3d-admin
  - nvidia
dependencies:
  - python=3.7
  - ipython
  - pip

  - numpy
  - scipy
  - pandas

  - matplotlib
  - seaborn

  - rdkit
  - openbabel
  - spyrmsd

  - cudatoolkit=11.1
  - pytorch

  - open3d
  - py3Dmol

  - jupyter

  - pip:
    - molgrid
